# Site settings
title: Ayres.io
email: admon@ayres.io
url: www.ayres.io
description: "Soporte y Escalamiento de Data Stack."
keywords: "data engineering databases relational nosql postgresql mysql mariadb clickhouse rethinkdb cockroachdb"
skills: "Soporte y Escalamiento de Data Stack."
meta_author: Ayres Data

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ""

menu:
  portfolio: "Servicios"
  about: "Nosotros"
  contact: "Contacto"

nosotros:
  p1: "El crecimiento de una empresa trae aparejado un mayor volumen de datos. Los tiempos de respuesta, seguridad y la disponibilidad de los servicios de datos en el backend comienzan a ser más críticos."
  p2: "Sabemos como ayudarlo en esto, años de experiencia y trabajo en clientes de envergadura nos han dado la experiencia para actuar en lo que su empresa necesita."
  button: "Nosotros"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 43B274  #80B3FF
  primary-rgb: "67,178,116" #"128,179,255"
  secondary: 373737  #FD6E8A
  secondary-dark: 373737 0 #A2122F

# Footer settings
footer:
  copyright: Ayres Data
  location: Buenos Aires
  social: ayresdata
  credits: Ayres Data

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ayresdata
    #  - title: facebook
    #url:
    #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
    #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/ayresdata

# Postal address (add as many lines as necessary)
address:
  - line: Av. Congreso y Av. Cabildo
  - line: Buenos Aires, Argentina

# Credits content
credits: 'Data matters.'

# Build settings
markdown: kramdown
permalink: pretty
